# Utils shared by SDR and NDR
# (to be extended to support other similar models, and renamed as appropriate)

from collections import namedtuple
import os

import geopandas
import pandas

from natcap.invest.spec import ModelSpec

from invest_reports.utils import RasterPlotConfig

TABLE_PAGINATION_THRESHOLD = 10

RasterPlotCaptionGroup = namedtuple(
    'RasterPlotCaptionGroup', ['inputs', 'outputs', 'intermediates'])


def build_raster_plot_configs(id_lookup_table, raster_plot_tuples):
    """Build RasterPlotConfigs for use in plotting input or output rasters.

    Args:
        id_lookup_table (dict): Where to look up each raster id to find its
            filepath. Typically this will be either the ``args`` dict that was
            passed to the model's ``execute`` method, or the ``FileRegistry``
            that was generated by the model run.
        raster_plot_tuples (list[tuple[str]]): A list of 2- and/or 3-tuples,
            each of which should contain the following:
            - first, the id of the raster (as defined in the model spec),
            - second, the datatype of the raster ('continuous', 'divergent',
              'nominal', 'binary', or 'binary_high_contrast'), and
            - third (optionally), the transform to apply to the colormap when
              plotting (either 'linear' or 'log'; will default to 'linear' if
              not specified).

    Returns:
        A list of ``RasterPlotConfig``s suitable for passing to
            ``invest_reports.utils.plot_and_base64_encode_rasters``.
    """
    raster_plot_configs = []
    for (raster_id, *other_args) in raster_plot_tuples:
        raster_path = id_lookup_table[raster_id]
        raster_plot_configs.append(RasterPlotConfig(raster_path, *other_args))
    return raster_plot_configs


def generate_results_table_from_vector(filepath, cols_to_sum):
    vector_df = geopandas.read_file(filepath)
    vector_df = vector_df.drop(columns=['geometry'])

    css_classes = ['datatable']
    (num_rows, _) = vector_df.shape
    if num_rows > TABLE_PAGINATION_THRESHOLD:
        css_classes.append('paginate')

    html_table_totals = None
    if num_rows > 1:
        totals_df = pandas.DataFrame()
        totals_df.loc['Totals', cols_to_sum] = vector_df.sum(axis=0)
        html_table_totals = totals_df.to_html(
            index=True, index_names=True, na_rep='', classes='full-width')

    html_table_main = vector_df.to_html(
        index=False, na_rep='', classes=css_classes)

    return (html_table_main, html_table_totals)


def generate_caption_from_raster_list(
        raster_list: list[tuple[str, str]], args_dict,
        file_registry, model_spec: ModelSpec):
    caption = []
    for (id, input_or_output) in raster_list:
        if input_or_output == 'input':
            filename = os.path.basename(args_dict[id])
            about_text = model_spec.get_input(id).about
        elif input_or_output == 'output':
            about_text = model_spec.get_output(id).about
            filename = os.path.basename(file_registry[id])
        caption.append(f'{filename}:{about_text}')
    return caption


def update_caption_with_stream_map_info(caption: list[str], flow_dir_alg: str):
    stream_map_info = (
        f' Results were generated using the {flow_dir_alg.upper()} flow '
        'direction algorithm. The stream network may look incomplete at '
        'this resolution, and therefore it may be necessary to view the '
        'full-resolution raster in GIS to assess its accuracy.')
    return [
        (list_item + stream_map_info
            if list_item.startswith('stream')
            else list_item)
        for list_item in caption]
