# Shared report generator for SDR and NDR
# (to be extended to support other similar models, and renamed as appropriate)

import json
import logging
import os
import sys
import time

import invest_reports.utils
from invest_reports import jinja_env
from invest_reports import sdr_ndr_utils

LOGGER = logging.getLogger(__name__)

TEMPLATE = jinja_env.get_template('sdr-ndr-report.html')


def report(file_registry, args_dict, model_spec, target_html_filepath):
    """Generate an HTML summary of model results.

    Args:
        file_registry (dict): The ``natcap.invest.FileRegistry.registry``
            that was returned by the model's ``execute`` method.
        args_dict (dict): The arguments that were passed to the model's
            ``execute`` method.
        model_spec (natcap.invest.spec.ModelSpec): the model's ``MODEL_SPEC``.
        target_html_filepath (str): path to an HTML file to be generated by
            this function.

    Returns:
        ``None``
    """

    model_id = model_spec.model_id

    inputs_img_src = invest_reports.utils.plot_and_base64_encode_rasters(
        sdr_ndr_utils.get_input_raster_plot_configs(model_id, args_dict))

    outputs_img_src = invest_reports.utils.plot_and_base64_encode_rasters(
        sdr_ndr_utils.get_output_raster_plot_configs(
            model_id, args_dict, file_registry))

    intermediate_img_src = invest_reports.utils.plot_and_base64_encode_rasters(
        sdr_ndr_utils.get_intermediate_output_raster_plot_configs(
            model_id, args_dict, file_registry))

    ws_vector_table = sdr_ndr_utils.generate_watershed_results_table(
        model_id, file_registry)

    output_raster_stats_table = invest_reports.utils.raster_workspace_summary(
        args_dict['workspace_dir']).to_html(na_rep='')

    input_raster_stats_table = invest_reports.utils.raster_inputs_summary(
        args_dict).to_html(na_rep='')

    stats_table_note = (
        '"Valid percent" indicates the percent of pixels that are not '
        'nodata. Comparing "valid percent" values across rasters may help '
        'you identify cases of unexpected nodata.'
    )

    with open(target_html_filepath, 'w', encoding='utf-8') as target_file:
        target_file.write(TEMPLATE.render(
            report_script=__file__,
            model_id=model_spec.model_id,
            model_name=model_spec.model_title,
            userguide_page=model_spec.userguide,
            timestamp=time.strftime('%Y-%m-%d %H:%M'),
            args_dict=args_dict,
            inputs_img_src=inputs_img_src,
            outputs_img_src=outputs_img_src,
            intermediate_outputs_heading='Stream Network Maps',
            intermediate_outputs_img_src=intermediate_img_src,
            ws_vector_table=ws_vector_table,
            output_raster_stats_table=output_raster_stats_table,
            input_raster_stats_table=input_raster_stats_table,
            stats_table_note=stats_table_note,
            model_spec_outputs=model_spec.outputs,
            accordions_open_on_load=True,
        ))


# @TODO: remove this block for InVEST Workbench integration
if __name__ == '__main__':
    from natcap.invest.ndr.ndr import MODEL_SPEC
    # from natcap.invest.sdr.sdr import MODEL_SPEC
    import natcap.invest.datastack
    handler = logging.StreamHandler(sys.stdout)
    logging.basicConfig(level=logging.INFO, handlers=[handler])
    logfile_path = '/Users/eadavis/invest-workspaces/ndr/InVEST-ndr-log-2025-12-01--15_34_31.txt'
    # logfile_path = '/Users/eadavis/invest-workspaces/sdr/InVEST-sdr-log-2025-10-29--15_26_12.txt'
    _, ds_info = natcap.invest.datastack.get_datastack_info(logfile_path)
    args_dict = MODEL_SPEC.preprocess_inputs(ds_info.args)
    file_registry_path = os.path.join(
        args_dict['workspace_dir'],
        f'file_registry{args_dict['results_suffix']}.json')

    with open(file_registry_path, 'r') as file:
        file_registry = json.loads(file.read())

    target_filepath = os.path.join(
        args_dict['workspace_dir'],
        f'{MODEL_SPEC.model_id.lower()}_report{args_dict['results_suffix']}.html')

    report(file_registry, args_dict, MODEL_SPEC, target_filepath)
