# Shared report generator for SDR and NDR
# (to be extended to support other similar models, and renamed as appropriate)

import logging
import time

import invest_reports.utils
from invest_reports import jinja_env
from invest_reports import sdr_ndr_utils
from invest_reports.utils import RasterPlotConfigGroup

LOGGER = logging.getLogger(__name__)

TEMPLATE = jinja_env.get_template('sdr-ndr-report.html')


def report(file_registry, args_dict, model_spec, target_html_filepath,
           raster_plot_configs: RasterPlotConfigGroup):
    """Generate an HTML summary of model results.

    Args:
        file_registry (dict): The ``natcap.invest.FileRegistry.registry``
            that was returned by the model's ``execute`` method.
        args_dict (dict): The arguments that were passed to the model's
            ``execute`` method.
        model_spec (natcap.invest.spec.ModelSpec): the model's ``MODEL_SPEC``.
        target_html_filepath (str): path to an HTML file to be generated by
            this function.
        raster_plot_configs (``RasterPlotConfigGroup``): ``RasterPlotConfig``s
            to be used to plot input, output, and intermediate output rasters.

    Returns:
        ``None``
    """

    model_id = model_spec.model_id

    inputs_img_src = invest_reports.utils.plot_and_base64_encode_rasters(
        raster_plot_configs.inputs)

    outputs_img_src = invest_reports.utils.plot_and_base64_encode_rasters(
        raster_plot_configs.outputs)

    intermediate_img_src = invest_reports.utils.plot_and_base64_encode_rasters(
        raster_plot_configs.intermediates)

    ws_vector_table = sdr_ndr_utils.generate_watershed_results_table(
        model_id, file_registry)

    output_raster_stats_table = invest_reports.utils.raster_workspace_summary(
        args_dict['workspace_dir']).to_html(na_rep='')

    input_raster_stats_table = invest_reports.utils.raster_inputs_summary(
        args_dict).to_html(na_rep='')

    stats_table_note = (
        '"Valid percent" indicates the percent of pixels that are not '
        'nodata. Comparing "valid percent" values across rasters may help '
        'you identify cases of unexpected nodata.'
    )

    with open(target_html_filepath, 'w', encoding='utf-8') as target_file:
        target_file.write(TEMPLATE.render(
            report_script=__file__,
            model_id=model_spec.model_id,
            model_name=model_spec.model_title,
            userguide_page=model_spec.userguide,
            timestamp=time.strftime('%Y-%m-%d %H:%M'),
            args_dict=args_dict,
            inputs_img_src=inputs_img_src,
            outputs_img_src=outputs_img_src,
            intermediate_outputs_heading='Stream Network Maps',
            intermediate_outputs_img_src=intermediate_img_src,
            ws_vector_table=ws_vector_table,
            output_raster_stats_table=output_raster_stats_table,
            input_raster_stats_table=input_raster_stats_table,
            stats_table_note=stats_table_note,
            model_spec_outputs=model_spec.outputs,
            accordions_open_on_load=True,
        ))
