import json
import logging
import os
import sys

from invest_reports import sdr_ndr_utils
from invest_reports.jinja_report_generators import sdr_ndr_report_generator
from invest_reports.utils import RasterPlotConfigGroup

LOGGER = logging.getLogger(__name__)

INPUT_RASTER_PLOT_TUPLES = [
    ('dem_path', 'continuous'),
    ('erodibility_path', 'continuous'),
    ('erosivity_path', 'continuous'),
    ('lulc_path', 'nominal'),
]

OUTPUT_RASTER_PLOT_TUPLES = [
    ('avoided_erosion', 'continuous', 'linear'),
    ('avoided_export', 'continuous', 'log'),
    ('sed_deposition', 'continuous', 'log'),
    ('sed_export', 'continuous', 'log'),
    ('rkls', 'continuous', 'linear'),
    ('usle', 'continuous', 'log'),
]

INTERMEDIATE_OUTPUT_RASTER_PLOT_TUPLES = [
    ('pit_filled_dem', 'continuous'),
    ('what_drains_to_stream', 'binary'),
]


def report(file_registry, args_dict, model_spec, target_html_filepath):
    """Generate an HTML summary of model results.

    Args:
        file_registry (dict): The ``natcap.invest.FileRegistry.registry``
            that was returned by the model's ``execute`` method.
        args_dict (dict): The arguments that were passed to the model's
            ``execute`` method.
        model_spec (natcap.invest.spec.ModelSpec): the model's ``MODEL_SPEC``.
        target_html_filepath (str): path to an HTML file to be generated by
            this function.

    Returns:
        ``None``
    """

    input_raster_plot_configs = sdr_ndr_utils.build_input_raster_plot_configs(
        args_dict, INPUT_RASTER_PLOT_TUPLES)

    output_raster_plot_configs = sdr_ndr_utils.build_output_raster_plot_configs(
        file_registry, OUTPUT_RASTER_PLOT_TUPLES)

    intermediate_raster_plot_configs = sdr_ndr_utils.build_intermediate_output_raster_plot_configs(
        args_dict, file_registry, INTERMEDIATE_OUTPUT_RASTER_PLOT_TUPLES)

    raster_plot_configs = RasterPlotConfigGroup(
        input_raster_plot_configs,
        output_raster_plot_configs,
        intermediate_raster_plot_configs)

    results_vector_id = 'watershed_results_sdr'
    results_vector_cols_to_sum = [
        'usle_tot', 'sed_export', 'sed_dep', 'avoid_exp', 'avoid_eros']

    sdr_ndr_report_generator.report(
        file_registry, args_dict, model_spec, target_html_filepath,
        raster_plot_configs, results_vector_id, results_vector_cols_to_sum)


# @TODO: remove this block for InVEST Workbench integration
if __name__ == '__main__':
    from natcap.invest.sdr.sdr import MODEL_SPEC
    import natcap.invest.datastack
    handler = logging.StreamHandler(sys.stdout)
    logging.basicConfig(level=logging.INFO, handlers=[handler])
    logfile_path = '/Users/eadavis/invest-workspaces/sdr/InVEST-sdr-log-2025-10-29--15_26_12.txt'
    _, ds_info = natcap.invest.datastack.get_datastack_info(logfile_path)
    args_dict = MODEL_SPEC.preprocess_inputs(ds_info.args)
    file_registry_path = os.path.join(
        args_dict['workspace_dir'],
        f'file_registry{args_dict['results_suffix']}.json')

    with open(file_registry_path, 'r') as file:
        file_registry = json.loads(file.read())

    target_filepath = os.path.join(
        args_dict['workspace_dir'],
        f'{MODEL_SPEC.model_id.lower()}_report{args_dict['results_suffix']}.html')

    report(file_registry, args_dict, MODEL_SPEC, target_filepath)
