# Shared report generator for SDR and NDR
# (to be extended to support other similar models, and renamed as appropriate)

import logging
import time

from invest_reports import jinja_env, sdr_ndr_utils, utils
from invest_reports.utils import RasterPlotConfigGroup

LOGGER = logging.getLogger(__name__)

TEMPLATE = jinja_env.get_template('sdr-ndr-report.html')


def report(file_registry, args_dict, model_spec, target_html_filepath,
           raster_plot_configs: RasterPlotConfigGroup, results_vector_id,
           results_vector_cols_to_sum):
    """Generate an HTML summary of model results.

    Args:
        file_registry (dict): the ``natcap.invest.FileRegistry.registry``
            that was returned by the model's ``execute`` method.
        args_dict (dict): the arguments that were passed to the model's
            ``execute`` method.
        model_spec (natcap.invest.spec.ModelSpec): the model's ``MODEL_SPEC``.
        target_html_filepath (str): path to an HTML file to be generated by
            this function.
        raster_plot_configs (``RasterPlotConfigGroup``): ``RasterPlotConfig``s
            to be used to plot input, output, and intermediate output rasters.
        results_vector_id (str): id of the results vector generated by the
            model (e.g., for NDR, ``watershed_results_ndr``),
        results_vector_cols_to_sum (list[str]): list of column names in the
            results vector to include when calculating totals.

    Returns:
        ``None``
    """

    inputs_img_src = utils.plot_and_base64_encode_rasters(
        raster_plot_configs.inputs)

    outputs_img_src = utils.plot_and_base64_encode_rasters(
        raster_plot_configs.outputs)

    intermediate_img_src = utils.plot_and_base64_encode_rasters(
        raster_plot_configs.intermediates)

    (ws_vector_table, ws_vector_totals_table) = (
        sdr_ndr_utils.generate_results_table_from_vector(
            file_registry[results_vector_id], results_vector_cols_to_sum))

    output_raster_stats_table = utils.raster_workspace_summary(
        file_registry).to_html(na_rep='')

    input_raster_stats_table = utils.raster_inputs_summary(
        args_dict).to_html(na_rep='')

    stats_table_note = (
        '"Valid percent" indicates the percent of pixels that are not '
        'nodata. Comparing "valid percent" values across rasters may help '
        'you identify cases of unexpected nodata.'
    )

    with open(target_html_filepath, 'w', encoding='utf-8') as target_file:
        target_file.write(TEMPLATE.render(
            report_script=__file__,
            model_id=model_spec.model_id,
            model_name=model_spec.model_title,
            userguide_page=model_spec.userguide,
            timestamp=time.strftime('%Y-%m-%d %H:%M'),
            args_dict=args_dict,
            inputs_img_src=inputs_img_src,
            outputs_img_src=outputs_img_src,
            intermediate_outputs_heading='Stream Network Maps',
            intermediate_outputs_img_src=intermediate_img_src,
            ws_vector_table=ws_vector_table,
            ws_vector_totals_table=ws_vector_totals_table,
            output_raster_stats_table=output_raster_stats_table,
            input_raster_stats_table=input_raster_stats_table,
            stats_table_note=stats_table_note,
            model_spec_outputs=model_spec.outputs,
        ))

    LOGGER.info(f'Created {target_html_filepath}')
